import { buildKit, VFX, type Skill, type SkillEffect } from "./skills";

export type {
  EffectType,
  SkillEffect,
  Skill,
  DefenseKind,
  DefenseSpec,
} from "./skills";
export { EFFECT_LABEL, MAX_LOADOUT, defaultLoadout } from "./skills";

export interface Ratios {
  hp: number;
  mp: number;
  str: number;
  def: number;
  ag: number;
  mv: number; // multiplicador de ouro
  xv: number; // multiplicador de xp
}

export type Rarity = "bronze" | "silver" | "gold";

export interface RobotDef {
  id: string;
  name: string;
  element: string;
  rarity: Rarity;
  ratios: Ratios;
  skills: Skill[];
  bio: string;
}

interface Blueprint {
  id: string;
  name: string;
  element: string;
  rarity: Rarity;
  ratios: Ratios;
  bio: string;
  vfxStrong: string;
  vfxSpecial: string;
  names: [string, string, string, string];
  effect: SkillEffect;
}

function buildSkills(b: Blueprint): Skill[] {
  return buildKit({
    id: b.id,
    element: b.element,
    names: b.names,
    effect: b.effect,
    vfxStrong: b.vfxStrong,
    vfxSpecial: b.vfxSpecial,
  });
}

const BLUEPRINTS: Blueprint[] = [
  {
    id: "aurorion",
    name: "AURORION",
    element: "LUZ",
    rarity: "gold",
    ratios: { hp: 105, mp: 110, str: 115, def: 105, ag: 108, mv: 12, xv: 14 },
    bio: "Cavaleiro de plasma solar. Lâmina de luz que corta blindagem.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.levelup,
    names: ["CORTE AURORA", "LAMINA SOLAR", "JULGAMENTO DE LUZ", "EGIDE RADIANTE"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.7 },
  },
  {
    id: "ferrovax",
    name: "FERROVAX",
    element: "FERRO",
    rarity: "bronze",
    ratios: { hp: 120, mp: 85, str: 112, def: 115, ag: 82, mv: 10, xv: 10 },
    bio: "Brigão industrial. Punhos de ferro fundido e chassi reforçado.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["SOCO PESADO", "MARTELO DE FERRO", "PRENSA HIDRAULICA", "POSTURA DE FERRO"],
    effect: { type: "weakening", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "cryolance",
    name: "CRYOLANCE",
    element: "GELO",
    rarity: "silver",
    ratios: { hp: 98, mp: 115, str: 105, def: 100, ag: 112, mv: 11, xv: 11 },
    bio: "Lanceiro criogênico. Congela sistemas inimigos em pleno combate.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["ESTOCADA GLACIAL", "LANCA DE GELO", "PRISAO CONGELANTE", "COURACA DE GELO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "voltronin",
    name: "VOLT RONIN",
    element: "TROVAO",
    rarity: "silver",
    ratios: { hp: 96, mp: 108, str: 118, def: 92, ag: 120, mv: 11, xv: 12 },
    bio: "Samurai eletrificado. Katana de arco voltaico e velocidade brutal.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["CORTE RAPIDO", "KATANA VOLTAICA", "TEMPESTADE DE AÇO", "GUARDA ESTATICA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.55 },
  },
  {
    id: "pyrokaiser",
    name: "PYROKAISER",
    element: "FOGO",
    rarity: "gold",
    ratios: { hp: 108, mp: 105, str: 122, def: 100, ag: 96, mv: 13, xv: 14 },
    bio: "Imperador incandescente. Núcleo de magma sob armadura de obsidiana.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["GARRA ARDENTE", "PUNHO DE MAGMA", "CORONHA INFERNAL", "MANTO DE BRASAS"],
    effect: { type: "burn", power: 8, turns: 4, chance: 0.85 },
  },
  {
    id: "terrabyte",
    name: "TERRABYTE",
    element: "TERRA",
    rarity: "bronze",
    ratios: { hp: 130, mp: 90, str: 104, def: 124, ag: 74, mv: 10, xv: 10 },
    bio: "Golem de rocha e musgo. Praticamente indestrutível.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.shield,
    names: ["PANCADA DE PEDRA", "AVALANCHE", "PRISAO DE ROCHA", "MURALHA VIVA"],
    effect: { type: "trapped", power: 0, turns: 2, chance: 0.6 },
  },
  {
    id: "zephyrblade",
    name: "ZEPHYRBLADE",
    element: "VENTO",
    rarity: "silver",
    ratios: { hp: 92, mp: 112, str: 108, def: 88, ag: 128, mv: 11, xv: 12 },
    bio: "Turbinas gêmeas nas costas. Dita o ritmo de qualquer luta.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.slash,
    names: ["LAMINA DE AR", "CICLONE DUPLO", "VENTO CORTANTE", "BARREIRA DE VENTO"],
    effect: { type: "blind", power: 30, turns: 3, chance: 0.7 },
  },
  {
    id: "nullshade",
    name: "NULLSHADE",
    element: "VAZIO",
    rarity: "gold",
    ratios: { hp: 94, mp: 120, str: 124, def: 86, ag: 122, mv: 14, xv: 15 },
    bio: "Assassino do vazio. Dilacera código e blindagem por igual.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["GARRA SOMBRIA", "FENDA DO VAZIO", "COLAPSO NULO", "MANTO DE SOMBRA"],
    effect: { type: "drain", power: 12, turns: 3, chance: 0.8 },
  },
  {
    id: "acidra",
    name: "ACIDRA",
    element: "ACIDO",
    rarity: "bronze",
    ratios: { hp: 100, mp: 108, str: 106, def: 96, ag: 106, mv: 10, xv: 11 },
    bio: "Tanque químico ambulante. Dissolve armaduras lentamente.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.void,
    names: ["JATO CORROSIVO", "CANHAO DE ACIDO", "CHUVA TOXICA", "SELO QUIMICO"],
    effect: { type: "poison", power: 10, turns: 4, chance: 0.85 },
  },
  {
    id: "gravitus",
    name: "GRAVITUS",
    element: "GRAVIDADE",
    rarity: "silver",
    ratios: { hp: 104, mp: 118, str: 110, def: 104, ag: 100, mv: 12, xv: 12 },
    bio: "Flutua acima do solo manipulando o próprio peso do inimigo.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.impact,
    names: ["PULSO GRAVE", "ESMAGAMENTO G", "POCO GRAVITACIONAL", "CAMPO DE PESO"],
    effect: { type: "trapped", power: 0, turns: 2, chance: 0.65 },
  },
  {
    id: "chronowake",
    name: "CHRONOWAKE",
    element: "TEMPO",
    rarity: "gold",
    ratios: { hp: 96, mp: 126, str: 112, def: 98, ag: 118, mv: 14, xv: 15 },
    bio: "Engrenagens temporais. Rouba turnos e desacelera adversários.",
    vfxStrong: VFX.levelup,
    vfxSpecial: VFX.shield,
    names: ["GOLPE ATRASADO", "ENGRENAGEM FINAL", "ESTASE TEMPORAL", "REVERSAO CURTA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.6 },
  },
  {
    id: "bioreaper",
    name: "BIOREAPER",
    element: "BIO",
    rarity: "silver",
    ratios: { hp: 106, mp: 104, str: 118, def: 94, ag: 108, mv: 11, xv: 12 },
    bio: "Bio-máquina com foice de esporos. Se regenera enquanto ataca.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["FOICE CURTA", "CEIFA VERDE", "ESPOROS PARASITAS", "CASCA REGENERATIVA"],
    effect: { type: "poison", power: 12, turns: 3, chance: 0.8 },
  },
  {
    id: "stormfang",
    name: "STORMFANG",
    element: "TEMPESTADE",
    rarity: "silver",
    ratios: { hp: 102, mp: 106, str: 120, def: 94, ag: 116, mv: 12, xv: 12 },
    bio: "Besta-lobo de trovão. Caça em rajadas curtas e violentas.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["MORDIDA ELETRICA", "PRESA DE TROVAO", "UIVO DE TEMPESTADE", "PELAGEM ISOLANTE"],
    effect: { type: "weakening", power: 30, turns: 3, chance: 0.7 },
  },
  {
    id: "quartzine",
    name: "QUARTZINE",
    element: "CRISTAL",
    rarity: "bronze",
    ratios: { hp: 108, mp: 110, str: 102, def: 118, ag: 92, mv: 10, xv: 11 },
    bio: "Corpo de quartzo prismático. Reflete parte do impacto recebido.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["ESTILHACO", "LANCA PRISMATICA", "REFRACAO CEGANTE", "ARMADURA DE QUARTZO"],
    effect: { type: "blind", power: 35, turns: 3, chance: 0.75 },
  },
  {
    id: "hydroknight",
    name: "HYDROKNIGHT",
    element: "AGUA",
    rarity: "silver",
    ratios: { hp: 112, mp: 114, str: 106, def: 110, ag: 98, mv: 11, xv: 11 },
    bio: "Paladino aquático de tridente. Sustenta a linha de frente.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.heal,
    names: ["TRIDENTE RAPIDO", "MARE DE ACO", "CORRENTE CURATIVA", "ESCUDO DE AGUA"],
    effect: { type: "hp_regen", power: 8, turns: 4, chance: 1 },
  },
  {
    id: "emberfox",
    name: "EMBERFOX",
    element: "BRASA",
    rarity: "gold",
    ratios: { hp: 94, mp: 122, str: 120, def: 88, ag: 126, mv: 14, xv: 15 },
    bio: "Ninja-raposa de nove caudas em brasa. Golpes rápidos e ardentes.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["GARRA VELOZ", "NOVE CAUDAS", "FOGO FANTASMA", "VEU DE FUMACA"],
    effect: { type: "burn", power: 10, turns: 4, chance: 0.8 },
  },
  {
    id: "ironmonk",
    name: "IRONMONK",
    element: "JADE",
    rarity: "bronze",
    ratios: { hp: 110, mp: 100, str: 110, def: 112, ag: 104, mv: 10, xv: 11 },
    bio: "Monge marcial de bronze e jade. Disciplina acima da força bruta.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.shield,
    names: ["PALMA DE JADE", "COMBO TRIPLO", "TOQUE PARALISANTE", "MEDITACAO DE ACO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "nebulon",
    name: "NEBULON",
    element: "COSMICO",
    rarity: "gold",
    ratios: { hp: 100, mp: 130, str: 116, def: 100, ag: 110, mv: 14, xv: 16 },
    bio: "Mago cósmico com cajado estelar. Converte poeira estelar em dano.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.levelup,
    names: ["TOQUE ESTELAR", "NOVA COLAPSANTE", "CHUVA DE METEOROS", "AURA NEBULAR"],
    effect: { type: "drain", power: 14, turns: 3, chance: 0.8 },
  },
  {
    id: "titanox",
    name: "TITANOX",
    element: "TITA",
    rarity: "silver",
    ratios: { hp: 136, mp: 88, str: 116, def: 126, ag: 70, mv: 12, xv: 12 },
    bio: "Colosso de assalto com canhões de ombro. Anda por cima de tudo.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.impact,
    names: ["PUNHO COLOSSAL", "BARRAGEM DE OMBRO", "PISADA SISMICA", "BLINDAGEM TITA"],
    effect: { type: "weakening", power: 35, turns: 3, chance: 0.7 },
  },
  {
    id: "magnavore",
    name: "MAGNAVORE",
    element: "MAGNETISMO",
    rarity: "gold",
    ratios: { hp: 104, mp: 120, str: 122, def: 104, ag: 106, mv: 15, xv: 16 },
    bio: "Devora metal com campos magnéticos. Detritos orbitam seu chassi.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.thunder,
    names: ["PUXAO MAGNETICO", "TEMPESTADE DE SUCATA", "DESMAGNETIZAR", "CAMPO REPULSOR"],
    effect: { type: "drain", power: 16, turns: 3, chance: 0.8 },
  },  // --- ROSTER 100 ---
  {
    id: "solarixprime",
    name: "SOLARIX PRIME",
    element: "SOL",
    rarity: "gold",
    ratios: { hp: 98, mp: 118, str: 120, def: 101, ag: 110, mv: 14, xv: 15 },
    bio: "Chassi forjado para SOL. Abre a guarda inimiga com SUPERNOVA PRIME.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.levelup,
    names: ["CORTE SOLAR", "LAMINA DE HELIO", "SUPERNOVA PRIME", "ESCUDO FOTONICO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "lunargeist",
    name: "LUNAR GEIST",
    element: "LUA",
    rarity: "silver",
    ratios: { hp: 107, mp: 107, str: 118, def: 109, ag: 102, mv: 11, xv: 12 },
    bio: "Piloto autônomo de LUA. Guarda MALDICAO LUNAR para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["FOICE MINGUANTE", "LUZ DA LUA CHEIA", "MALDICAO LUNAR", "VEU DE ECLIPSE"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "dunecrawler",
    name: "DUNE CRAWLER",
    element: "AREIA",
    rarity: "bronze",
    ratios: { hp: 104, mp: 82, str: 101, def: 105, ag: 95, mv: 9, xv: 9 },
    bio: "Campeão de AREIA. Sua técnica AREIA MOVEDICA encerra duelos em um golpe.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.explosion,
    names: ["BROCA DE AREIA", "TEMPESTADE DE PO", "AREIA MOVEDICA", "CARAPACA DUNA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "junglemaw",
    name: "JUNGLE MAW",
    element: "SELVA",
    rarity: "silver",
    ratios: { hp: 105, mp: 106, str: 119, def: 99, ag: 115, mv: 11, xv: 12 },
    bio: "Predador de SELVA. Caça sistemas rivais e finaliza com ESPOROS TOXICOS.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["CHICOTE DE CIPO", "MORDIDA DA SELVA", "ESPOROS TOXICOS", "CASCA REFORCADA"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "abyssalord",
    name: "ABYSSA LORD",
    element: "ABISSO",
    rarity: "gold",
    ratios: { hp: 109, mp: 119, str: 117, def: 101, ag: 117, mv: 14, xv: 15 },
    bio: "Piloto autônomo de ABISSO. Guarda ISCA HIPNOTICA para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["TENTACULO ABISSAL", "PRESSAO DE MIL METROS", "ISCA HIPNOTICA", "COURACA DO ABISMO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "toxinvore",
    name: "TOXINVORE",
    element: "TOXINA",
    rarity: "bronze",
    ratios: { hp: 106, mp: 83, str: 112, def: 102, ag: 81, mv: 9, xv: 9 },
    bio: "Predador de TOXINA. Caça sistemas rivais e finaliza com PRAGA CORROSIVA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GARRA SEPTICA", "JATO DE TOXINA", "PRAGA CORROSIVA", "FILTRO BLINDADO"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "ruinwarden",
    name: "RUIN WARDEN",
    element: "RUINA",
    rarity: "silver",
    ratios: { hp: 100, mp: 101, str: 108, def: 99, ag: 108, mv: 11, xv: 12 },
    bio: "Piloto autônomo de RUINA. Guarda SELO ESQUECIDO para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["PANCADA DE RUINA", "GLIFO ANCESTRAL", "SELO ESQUECIDO", "MURALHA ETERNA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "forgeheart",
    name: "FORGE HEART",
    element: "FORJA",
    rarity: "silver",
    ratios: { hp: 99, mp: 96, str: 109, def: 101, ag: 115, mv: 11, xv: 12 },
    bio: "Predador de FORJA. Caça sistemas rivais e finaliza com METAL DERRETIDO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["MARTELO EM BRASA", "BIGORNA FUNDIDA", "METAL DERRETIDO", "TEMPERA DE ACO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "snowreaver",
    name: "SNOW REAVER",
    element: "NEVE",
    rarity: "bronze",
    ratios: { hp: 107, mp: 96, str: 97, def: 112, ag: 87, mv: 9, xv: 9 },
    bio: "Lenda do circuito de NEVE. Ninguém sobrevive a CONGELAMENTO duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GANCHO GELIDO", "NEVASCA CORTANTE", "CONGELAMENTO", "MANTO DE NEVE"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "ashenrevenant",
    name: "ASHEN REVENANT",
    element: "CINZAS",
    rarity: "gold",
    ratios: { hp: 99, mp: 123, str: 128, def: 107, ag: 107, mv: 14, xv: 15 },
    bio: "Veterano das arenas de CINZAS. Assina cada vitória com CREMACAO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GARRA DE CINZAS", "SOPRO INCANDESCENTE", "CREMACAO", "SUDARIO DE FUMACA"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "plasmawraith",
    name: "PLASMA WRAITH",
    element: "PLASMA",
    rarity: "gold",
    ratios: { hp: 104, mp: 117, str: 122, def: 111, ag: 114, mv: 14, xv: 15 },
    bio: "Predador de PLASMA. Caça sistemas rivais e finaliza com FUSAO INSTAVEL.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["LANCA DE PLASMA", "ARCO IONIZADO", "FUSAO INSTAVEL", "CAMPO DE CONTENCAO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "shadowfang",
    name: "SHADOWFANG",
    element: "SOMBRA",
    rarity: "silver",
    ratios: { hp: 100, mp: 101, str: 109, def: 106, ag: 112, mv: 11, xv: 12 },
    bio: "Campeão de SOMBRA. Sua técnica BREU ABSOLUTO encerra duelos em um golpe.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["MORDIDA SOMBRIA", "SALTO NOTURNO", "BREU ABSOLUTO", "MANTO DE SOMBRAS"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "mirrorclad",
    name: "MIRRORCLAD",
    element: "ESPELHO",
    rarity: "gold",
    ratios: { hp: 108, mp: 119, str: 126, def: 106, ag: 107, mv: 14, xv: 15 },
    bio: "Predador de ESPELHO. Caça sistemas rivais e finaliza com IMAGEM INVERTIDA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ESTILHACO ESPELHADO", "REFLEXO CORTANTE", "IMAGEM INVERTIDA", "BARREIRA REFLETORA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "bonemarshal",
    name: "BONE MARSHAL",
    element: "OSSO",
    rarity: "silver",
    ratios: { hp: 99, mp: 103, str: 116, def: 94, ag: 101, mv: 11, xv: 12 },
    bio: "Predador de OSSO. Caça sistemas rivais e finaliza com MEDULA DRENADA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["SABRE DE OSSO", "ORDEM MORTAL", "MEDULA DRENADA", "COSTELAS DE ACO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "cloudpiercer",
    name: "CLOUD PIERCER",
    element: "NUVEM",
    rarity: "bronze",
    ratios: { hp: 118, mp: 90, str: 107, def: 115, ag: 88, mv: 9, xv: 9 },
    bio: "Lenda do circuito de NUVEM. Ninguém sobrevive a VACUO DE ALTITUDE duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ESTOCADA AEREA", "FURA-NUVENS", "VACUO DE ALTITUDE", "CASULO DE VAPOR"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "vulcanargo",
    name: "VULCAN ARGO",
    element: "VULCAO",
    rarity: "silver",
    ratios: { hp: 103, mp: 108, str: 112, def: 94, ag: 108, mv: 11, xv: 12 },
    bio: "Predador de VULCAO. Caça sistemas rivais e finaliza com CHUVA DE LAPILLI.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["PUNHO DE MAGMA", "ERUPCAO", "CHUVA DE LAPILLI", "CROSTA VULCANICA"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "mireclad",
    name: "MIRECLAD",
    element: "PANTANO",
    rarity: "bronze",
    ratios: { hp: 115, mp: 82, str: 104, def: 114, ag: 86, mv: 9, xv: 9 },
    bio: "Campeão de PANTANO. Sua técnica MIASMA encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GARRA DE LODO", "ATOLEIRO", "MIASMA", "COURACA DE LIMO"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "aridfang",
    name: "ARID FANG",
    element: "DESERTO",
    rarity: "bronze",
    ratios: { hp: 117, mp: 95, str: 99, def: 114, ag: 97, mv: 9, xv: 9 },
    bio: "Piloto autônomo de DESERTO. Guarda VENENO SECO para o momento decisivo.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.explosion,
    names: ["FERRAO ARIDO", "PINCA DUPLA", "VENENO SECO", "CARAPACA ESCALDANTE"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "tundrakeeper",
    name: "TUNDRA KEEPER",
    element: "TUNDRA",
    rarity: "silver",
    ratios: { hp: 98, mp: 103, str: 110, def: 101, ag: 115, mv: 11, xv: 12 },
    bio: "Predador de TUNDRA. Caça sistemas rivais e finaliza com GEADA PROFUNDA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["MACA GLACIAL", "VENTO DA TUNDRA", "GEADA PROFUNDA", "MURO DE GELO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "reefsovereign",
    name: "REEF SOVEREIGN",
    element: "RECIFE",
    rarity: "gold",
    ratios: { hp: 106, mp: 110, str: 123, def: 112, ag: 119, mv: 14, xv: 15 },
    bio: "Veterano das arenas de RECIFE. Assina cada vitória com POLIPO PARASITA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["TRIDENTE DE CORAL", "MARE VIVA", "POLIPO PARASITA", "CONCHA REAL"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "obsidianfist",
    name: "OBSIDIAN FIST",
    element: "OBSIDIANA",
    rarity: "silver",
    ratios: { hp: 104, mp: 105, str: 109, def: 98, ag: 104, mv: 11, xv: 12 },
    bio: "Lenda do circuito de OBSIDIANA. Ninguém sobrevive a CORTE VITREO duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["PUNHO DE OBSIDIANA", "ESTILHACO NEGRO", "CORTE VITREO", "PLACA VULCANICA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "amberlock",
    name: "AMBERLOCK",
    element: "AMBAR",
    rarity: "bronze",
    ratios: { hp: 109, mp: 90, str: 104, def: 114, ag: 86, mv: 9, xv: 9 },
    bio: "Predador de AMBAR. Caça sistemas rivais e finaliza com FOSSILIZAR.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["RESINA ENDURECIDA", "SELO DE AMBAR", "FOSSILIZAR", "CASULO DOURADO"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "neondrifter",
    name: "NEON DRIFTER",
    element: "NEON",
    rarity: "silver",
    ratios: { hp: 99, mp: 103, str: 112, def: 108, ag: 101, mv: 11, xv: 12 },
    bio: "Predador de NEON. Caça sistemas rivais e finaliza com SOBRECARGA LUMINOSA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CORTE NEON", "DERRAPAGEM", "SOBRECARGA LUMINOSA", "GRADE DE LUZ"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "rustpriest",
    name: "RUST PRIEST",
    element: "FERRUGEM",
    rarity: "bronze",
    ratios: { hp: 104, mp: 81, str: 100, def: 105, ag: 96, mv: 9, xv: 9 },
    bio: "Campeão de FERRUGEM. Sua técnica OXIDACAO encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CORRENTE ENFERRUJADA", "BENCAO CORROSIVA", "OXIDACAO", "MANTO OXIDADO"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "graphenex",
    name: "GRAPHENEX",
    element: "GRAFENO",
    rarity: "gold",
    ratios: { hp: 104, mp: 119, str: 115, def: 110, ag: 109, mv: 14, xv: 15 },
    bio: "Chassi forjado para GRAFENO. Abre a guarda inimiga com COLAPSO ATOMICO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["LAMINA HEXAGONAL", "MALHA CORTANTE", "COLAPSO ATOMICO", "ESCUDO MONOCAMADA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "quantumecho",
    name: "QUANTUM ECHO",
    element: "QUANTUM",
    rarity: "gold",
    ratios: { hp: 104, mp: 114, str: 117, def: 113, ag: 112, mv: 14, xv: 15 },
    bio: "Lenda do circuito de QUANTUM. Ninguém sobrevive a COLAPSO DE ONDA duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["SOCO DEFASADO", "SUPERPOSICAO", "COLAPSO DE ONDA", "INCERTEZA"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "nebulaseer",
    name: "NEBULA SEER",
    element: "NEBULOSA",
    rarity: "silver",
    ratios: { hp: 107, mp: 112, str: 116, def: 106, ag: 107, mv: 11, xv: 12 },
    bio: "Chassi forjado para NEBULOSA. Abre a guarda inimiga com VISAO DO VAZIO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["FEIXE ESTELAR", "VENTO NEBULAR", "VISAO DO VAZIO", "AURA COSMICA"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "eclipsar",
    name: "ECLIPSAR",
    element: "ECLIPSE",
    rarity: "gold",
    ratios: { hp: 98, mp: 112, str: 119, def: 99, ag: 110, mv: 14, xv: 15 },
    bio: "Piloto autônomo de ECLIPSE. Guarda SOMBRA SOLAR para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ANEL DE CORONA", "TOTALIDADE", "SOMBRA SOLAR", "UMBRA PROTETORA"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "meteorpunch",
    name: "METEOR PUNCH",
    element: "METEORO",
    rarity: "silver",
    ratios: { hp: 108, mp: 100, str: 113, def: 104, ag: 104, mv: 11, xv: 12 },
    bio: "Campeão de METEORO. Sua técnica CHUVA DE ROCHAS encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["SOCO METEORO", "IMPACTO DE CRATERA", "CHUVA DE ROCHAS", "CASCA CARBONIZADA"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "ringwarden",
    name: "RING WARDEN",
    element: "ANEL",
    rarity: "silver",
    ratios: { hp: 112, mp: 107, str: 111, def: 107, ag: 103, mv: 11, xv: 12 },
    bio: "Predador de ANEL. Caça sistemas rivais e finaliza com GRAVIDADE DE ANEL.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["DISCO ORBITAL", "ANEL CORTANTE", "GRAVIDADE DE ANEL", "ORBITA DEFENSIVA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "pulsarcore",
    name: "PULSAR CORE",
    element: "PULSAR",
    rarity: "gold",
    ratios: { hp: 107, mp: 118, str: 118, def: 99, ag: 113, mv: 14, xv: 15 },
    bio: "Campeão de PULSAR. Sua técnica RADIOPULSO encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["FEIXE PULSAR", "ROTACAO ULTRAVELOZ", "RADIOPULSO", "CAMPO MAGNETAR"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "voidsingularity",
    name: "VOID SINGULARITY",
    element: "BURACO NEGRO",
    rarity: "gold",
    ratios: { hp: 110, mp: 109, str: 126, def: 113, ag: 119, mv: 14, xv: 15 },
    bio: "Predador de BURACO NEGRO. Caça sistemas rivais e finaliza com ESPAGUETIFICACAO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ATRACAO FATAL", "HORIZONTE DE EVENTOS", "ESPAGUETIFICACAO", "POCO GRAVITACIONAL"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "seraphcircuit",
    name: "SERAPH CIRCUIT",
    element: "LUZ",
    rarity: "gold",
    ratios: { hp: 105, mp: 124, str: 123, def: 105, ag: 105, mv: 14, xv: 15 },
    bio: "Veterano das arenas de LUZ. Assina cada vitória com JULGAMENTO DIGITAL.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.levelup,
    names: ["LAMINA SACRA", "SEIS ASAS", "JULGAMENTO DIGITAL", "AUREOLA BLINDADA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "cinderhound",
    name: "CINDERHOUND",
    element: "BRASA",
    rarity: "bronze",
    ratios: { hp: 117, mp: 81, str: 98, def: 113, ag: 92, mv: 9, xv: 9 },
    bio: "Veterano das arenas de BRASA. Assina cada vitória com RASTRO DE FAGULHAS.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["MORDIDA EM BRASA", "LATIDO IGNEO", "RASTRO DE FAGULHAS", "PELAGEM DE CARVAO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "glacierjaw",
    name: "GLACIER JAW",
    element: "GELO",
    rarity: "silver",
    ratios: { hp: 97, mp: 100, str: 119, def: 102, ag: 101, mv: 11, xv: 12 },
    bio: "Lenda do circuito de GELO. Ninguém sobrevive a PRISAO DE GELO duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["MANDIBULA GLACIAL", "AVALANCHE", "PRISAO DE GELO", "BLINDAGEM DE ICEBERG"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "stormlance",
    name: "STORMLANCE",
    element: "TEMPESTADE",
    rarity: "silver",
    ratios: { hp: 105, mp: 110, str: 113, def: 94, ag: 99, mv: 11, xv: 12 },
    bio: "Lenda do circuito de TEMPESTADE. Ninguém sobrevive a DESCARGA EM CADEIA duas vezes.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["LANCA DE RAIO", "GALOPE DE TROVAO", "DESCARGA EM CADEIA", "PARA-RAIOS"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "terraforge",
    name: "TERRAFORGE",
    element: "TERRA",
    rarity: "bronze",
    ratios: { hp: 119, mp: 88, str: 98, def: 114, ag: 81, mv: 9, xv: 9 },
    bio: "Predador de TERRA. Caça sistemas rivais e finaliza com TREMOR.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["BRITADEIRA", "LEVANTE DE ROCHA", "TREMOR", "PLACA TECTONICA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "windshear",
    name: "WINDSHEAR",
    element: "VENTO",
    rarity: "bronze",
    ratios: { hp: 112, mp: 95, str: 101, def: 106, ag: 87, mv: 9, xv: 9 },
    bio: "Lenda do circuito de VENTO. Ninguém sobrevive a VACUO duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.thunder,
    names: ["CORTE DE ASA", "RAJADA CORTANTE", "VACUO", "REDEMOINHO ESCUDO"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "voidcaller",
    name: "VOIDCALLER",
    element: "VAZIO",
    rarity: "silver",
    ratios: { hp: 100, mp: 104, str: 113, def: 108, ag: 104, mv: 11, xv: 12 },
    bio: "Predador de VAZIO. Caça sistemas rivais e finaliza com SUGAR ESSENCIA.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["MAO DO VAZIO", "CHAMADO PROFUNDO", "SUGAR ESSENCIA", "PORTAL DEFENSIVO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "acidbloom",
    name: "ACIDBLOOM",
    element: "ACIDO",
    rarity: "bronze",
    ratios: { hp: 113, mp: 83, str: 104, def: 118, ag: 81, mv: 9, xv: 9 },
    bio: "Veterano das arenas de ACIDO. Assina cada vitória com FLORACAO TOXICA.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.void,
    names: ["PETALA CORROSIVA", "JATO ACIDO", "FLORACAO TOXICA", "CALICE BLINDADO"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "gravitide",
    name: "GRAVITIDE",
    element: "GRAVIDADE",
    rarity: "silver",
    ratios: { hp: 112, mp: 110, str: 113, def: 100, ag: 108, mv: 11, xv: 12 },
    bio: "Chassi forjado para GRAVIDADE. Abre a guarda inimiga com COMPRESSAO.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.impact,
    names: ["ESFERA GRAVITICA", "MARE DE PESO", "COMPRESSAO", "BOLHA INERCIAL"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "chronofracture",
    name: "CHRONOFRACTURE",
    element: "TEMPO",
    rarity: "gold",
    ratios: { hp: 103, mp: 115, str: 117, def: 108, ag: 115, mv: 14, xv: 15 },
    bio: "Veterano das arenas de TEMPO. Assina cada vitória com PARADOXO.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.levelup,
    names: ["CORTE TEMPORAL", "REBOBINAR", "PARADOXO", "AMPULHETA BLINDADA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "biolattice",
    name: "BIOLATTICE",
    element: "BIO",
    rarity: "silver",
    ratios: { hp: 103, mp: 100, str: 115, def: 94, ag: 115, mv: 11, xv: 12 },
    bio: "Veterano das arenas de BIO. Assina cada vitória com INFECCAO.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["TENDAO CHICOTE", "CRESCIMENTO VORAZ", "INFECCAO", "CASCA REGENERATIVA"],
    effect: { type: "hp_regen", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "crystallux",
    name: "CRYSTALLUX",
    element: "CRISTAL",
    rarity: "gold",
    ratios: { hp: 114, mp: 118, str: 116, def: 101, ag: 105, mv: 14, xv: 15 },
    bio: "Piloto autônomo de CRISTAL. Guarda REFRACAO CEGANTE para o momento decisivo.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["FEIXE PRISMATICO", "LAMINA FACETADA", "REFRACAO CEGANTE", "GEODO BLINDADO"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "aquabastion",
    name: "AQUA BASTION",
    element: "AGUA",
    rarity: "silver",
    ratios: { hp: 100, mp: 110, str: 104, def: 107, ag: 97, mv: 11, xv: 12 },
    bio: "Lenda do circuito de AGUA. Ninguém sobrevive a CORRENTEZA duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["CANHAO DE AGUA", "MARTELO DE ONDA", "CORRENTEZA", "BARREIRA LIQUIDA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "emberwing",
    name: "EMBERWING",
    element: "FOGO",
    rarity: "bronze",
    ratios: { hp: 111, mp: 80, str: 106, def: 104, ag: 85, mv: 9, xv: 9 },
    bio: "Chassi forjado para FOGO. Abre a guarda inimiga com RENASCER EM FOGO.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["ASA FLAMEJANTE", "BICO INCANDESCENTE", "RENASCER EM FOGO", "PLUMAGEM DE BRASA"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "ironsentinel",
    name: "IRON SENTINEL",
    element: "FERRO",
    rarity: "bronze",
    ratios: { hp: 110, mp: 82, str: 97, def: 118, ag: 92, mv: 9, xv: 9 },
    bio: "Predador de FERRO. Caça sistemas rivais e finaliza com TRAVA DE ACO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.shield,
    names: ["INVESTIDA DE ESCUDO", "BASTAO DE FERRO", "TRAVA DE ACO", "POSTURA DE MURO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "thunderoni",
    name: "THUNDER ONI",
    element: "TROVAO",
    rarity: "silver",
    ratios: { hp: 104, mp: 112, str: 118, def: 103, ag: 98, mv: 11, xv: 12 },
    bio: "Predador de TROVAO. Caça sistemas rivais e finaliza com MARCA DO ONI.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["CLAVA TROVEJANTE", "URRO ELETRICO", "MARCA DO ONI", "ARMADURA DEMONIACA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "titanbulwark",
    name: "TITAN BULWARK",
    element: "TITA",
    rarity: "gold",
    ratios: { hp: 100, mp: 111, str: 127, def: 111, ag: 118, mv: 14, xv: 15 },
    bio: "Veterano das arenas de TITA. Assina cada vitória com CERCO TOTAL.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.shield,
    names: ["SALVA DUPLA", "PUNHO TITANICO", "CERCO TOTAL", "FORTALEZA MOVEL"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "magnashrike",
    name: "MAGNASHRIKE",
    element: "MAGNETISMO",
    rarity: "silver",
    ratios: { hp: 100, mp: 111, str: 115, def: 104, ag: 108, mv: 11, xv: 12 },
    bio: "Lenda do circuito de MAGNETISMO. Ninguém sobrevive a POLARIDADE INVERSA duas vezes.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.thunder,
    names: ["MERGULHO MAGNETICO", "BICO DE SUCATA", "POLARIDADE INVERSA", "CAMPO DE FERRO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "jadearbiter",
    name: "JADE ARBITER",
    element: "JADE",
    rarity: "gold",
    ratios: { hp: 106, mp: 118, str: 120, def: 111, ag: 114, mv: 14, xv: 15 },
    bio: "Chassi forjado para JADE. Abre a guarda inimiga com VEREDITO ANCESTRAL.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["TONFA GEMEA", "PALMA DE JADE", "VEREDITO ANCESTRAL", "POSTURA IMOVEL"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "cosmoveil",
    name: "COSMOVEIL",
    element: "COSMICO",
    rarity: "silver",
    ratios: { hp: 105, mp: 112, str: 118, def: 101, ag: 102, mv: 11, xv: 12 },
    bio: "Predador de COSMICO. Caça sistemas rivais e finaliza com CONSTELACAO.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.levelup,
    names: ["VEU ESTELAR", "DANCA ORBITAL", "CONSTELACAO", "MANTO DO COSMOS"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "sandwyrm",
    name: "SANDWYRM",
    element: "AREIA",
    rarity: "silver",
    ratios: { hp: 104, mp: 98, str: 114, def: 106, ag: 109, mv: 11, xv: 12 },
    bio: "Campeão de AREIA. Sua técnica VORTICE DE AREIA encerra duelos em um golpe.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.explosion,
    names: ["EMBOSCADA SUBTERRANEA", "MOEDOR CIRCULAR", "VORTICE DE AREIA", "ANEIS BLINDADOS"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "pyreconclave",
    name: "PYRE CONCLAVE",
    element: "FOGO",
    rarity: "gold",
    ratios: { hp: 101, mp: 111, str: 124, def: 108, ag: 114, mv: 14, xv: 15 },
    bio: "Veterano das arenas de FOGO. Assina cada vitória com PIRA FUNERARIA.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["BRASEIRO SAGRADO", "CONDENACAO IGNEA", "PIRA FUNERARIA", "CIRCULO DE CHAMAS"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "frostmonarch",
    name: "FROST MONARCH",
    element: "GELO",
    rarity: "gold",
    ratios: { hp: 104, mp: 124, str: 115, def: 99, ag: 119, mv: 14, xv: 15 },
    bio: "Piloto autônomo de GELO. Guarda INVERNO ETERNO para o momento decisivo.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["CETRO GLACIAL", "DECRETO CONGELANTE", "INVERNO ETERNO", "TRONO DE GELO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "voltcarnyx",
    name: "VOLTCARNYX",
    element: "TROVAO",
    rarity: "gold",
    ratios: { hp: 107, mp: 109, str: 118, def: 98, ag: 111, mv: 14, xv: 15 },
    bio: "Chassi forjado para TROVAO. Abre a guarda inimiga com TROVAO PRIMORDIAL.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["SOPRO TESLA", "GARRA VOLTAICA", "TROVAO PRIMORDIAL", "BOBINA DEFENSIVA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "quarrybreaker",
    name: "QUARRY BREAKER",
    element: "TERRA",
    rarity: "bronze",
    ratios: { hp: 111, mp: 89, str: 101, def: 102, ag: 81, mv: 9, xv: 9 },
    bio: "Predador de TERRA. Caça sistemas rivais e finaliza com DESLIZAMENTO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["BOLA DE DEMOLICAO", "BRITA", "DESLIZAMENTO", "ESCUDO DE PEDREIRA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "zephyrhalo",
    name: "ZEPHYR HALO",
    element: "VENTO",
    rarity: "gold",
    ratios: { hp: 114, mp: 109, str: 123, def: 105, ag: 102, mv: 14, xv: 15 },
    bio: "Lenda do circuito de VENTO. Ninguém sobrevive a OLHO DA TORMENTA duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.thunder,
    names: ["FITA CICLONE", "BENCAO DO VENTO", "OLHO DA TORMENTA", "ESCUDO DE BRISA"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "nullpriest",
    name: "NULL PRIEST",
    element: "VAZIO",
    rarity: "gold",
    ratios: { hp: 111, mp: 109, str: 127, def: 100, ag: 116, mv: 14, xv: 15 },
    bio: "Veterano das arenas de VAZIO. Assina cada vitória com APAGAR EXISTENCIA.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["PALMA NULA", "SERMAO SILENCIOSO", "APAGAR EXISTENCIA", "DOGMA VAZIO"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "venomcarapace",
    name: "VENOM CARAPACE",
    element: "TOXINA",
    rarity: "silver",
    ratios: { hp: 110, mp: 108, str: 108, def: 103, ag: 104, mv: 11, xv: 12 },
    bio: "Chassi forjado para TOXINA. Abre a guarda inimiga com GAS NEUROTOXICO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CHIFRE VENENOSO", "CARGA BLINDADA", "GAS NEUROTOXICO", "CARAPACA DUPLA"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "grimsprocket",
    name: "GRIM SPROCKET",
    element: "RUINA",
    rarity: "bronze",
    ratios: { hp: 110, mp: 81, str: 104, def: 111, ag: 84, mv: 9, xv: 9 },
    bio: "Lenda do circuito de RUINA. Ninguém sobrevive a COLAPSO MECANICO duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GANCHO DENTADO", "ENGRENAGEM QUEBRADA", "COLAPSO MECANICO", "SUCATA PROTETORA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "blastfurnace",
    name: "BLAST FURNACE",
    element: "FORJA",
    rarity: "gold",
    ratios: { hp: 99, mp: 119, str: 125, def: 105, ag: 108, mv: 14, xv: 15 },
    bio: "Piloto autônomo de FORJA. Guarda FUSAO TOTAL para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["JORRO FUNDIDO", "PORTA DA FORNALHA", "FUSAO TOTAL", "REVESTIMENTO REFRATARIO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "hailstriker",
    name: "HAILSTRIKER",
    element: "NEVE",
    rarity: "silver",
    ratios: { hp: 96, mp: 98, str: 108, def: 96, ag: 104, mv: 11, xv: 12 },
    bio: "Piloto autônomo de NEVE. Guarda TORMENTA BRANCA para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["BARRAGEM DE GRANIZO", "OBUS GELADO", "TORMENTA BRANCA", "REDOMA DE GRANIZO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "emberlash",
    name: "EMBERLASH",
    element: "BRASA",
    rarity: "bronze",
    ratios: { hp: 120, mp: 92, str: 108, def: 109, ag: 81, mv: 9, xv: 9 },
    bio: "Campeão de BRASA. Sua técnica MARCA A FOGO encerra duelos em um golpe.",
    vfxStrong: VFX.explosion,
    vfxSpecial: VFX.explosion,
    names: ["ACOITE EM BRASA", "CHICOTE FUNDIDO", "MARCA A FOGO", "ESPIRAL DE CINZAS"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "lumenblade",
    name: "LUMEN BLADE",
    element: "LUZ",
    rarity: "silver",
    ratios: { hp: 108, mp: 102, str: 114, def: 110, ag: 110, mv: 11, xv: 12 },
    bio: "Predador de LUZ. Caça sistemas rivais e finaliza com BRILHO OFUSCANTE.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.levelup,
    names: ["FLORETE DE LUZ", "ESTOCADA VELOZ", "BRILHO OFUSCANTE", "PARADA LUMINOSA"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "gloomtide",
    name: "GLOOMTIDE",
    element: "ABISSO",
    rarity: "silver",
    ratios: { hp: 97, mp: 102, str: 110, def: 97, ag: 103, mv: 11, xv: 12 },
    bio: "Campeão de ABISSO. Sua técnica PULMAO INUNDADO encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["AGARRAO AFOGADO", "MARE ESCURA", "PULMAO INUNDADO", "CASCO ENCRUSTADO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "sporeherald",
    name: "SPORE HERALD",
    element: "BIO",
    rarity: "bronze",
    ratios: { hp: 107, mp: 95, str: 98, def: 107, ag: 79, mv: 9, xv: 9 },
    bio: "Veterano das arenas de BIO. Assina cada vitória com NUVEM FUNGICA.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["EXPLOSAO DE ESPOROS", "MICELIO INVASOR", "NUVEM FUNGICA", "CAPA DE MUSGO"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "prismvector",
    name: "PRISM VECTOR",
    element: "CRISTAL",
    rarity: "silver",
    ratios: { hp: 98, mp: 98, str: 108, def: 105, ag: 112, mv: 11, xv: 12 },
    bio: "Veterano das arenas de CRISTAL. Assina cada vitória com DISPERSAO.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.shield,
    names: ["SALVA DE ESTILHACOS", "VETOR CORTANTE", "DISPERSAO", "CONSTRUCTO CRISTALINO"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "maelstromfist",
    name: "MAELSTROM FIST",
    element: "AGUA",
    rarity: "gold",
    ratios: { hp: 100, mp: 116, str: 127, def: 109, ag: 104, mv: 14, xv: 15 },
    bio: "Lenda do circuito de AGUA. Ninguém sobrevive a AFOGAMENTO duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["SOCO REDEMOINHO", "GOLPE MAELSTROM", "AFOGAMENTO", "ESPIRAL DEFENSIVA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "scrapbaron",
    name: "SCRAP BARON",
    element: "FERRUGEM",
    rarity: "silver",
    ratios: { hp: 106, mp: 106, str: 114, def: 99, ag: 107, mv: 11, xv: 12 },
    bio: "Lenda do circuito de FERRUGEM. Ninguém sobrevive a PRENSA HIDRAULICA duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["GARRA DE GRUA", "FERRO-VELHO", "PRENSA HIDRAULICA", "MONTE DE SUCATA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "stelladrake",
    name: "STELLADRAKE",
    element: "COSMICO",
    rarity: "gold",
    ratios: { hp: 107, mp: 117, str: 128, def: 99, ag: 116, mv: 14, xv: 15 },
    bio: "Veterano das arenas de COSMICO. Assina cada vitória com NOVA DRACONICA.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.levelup,
    names: ["SOPRO ESTELAR", "GARRA DE COMETA", "NOVA DRACONICA", "ESCAMAS SIDERAIS"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "terminuscore",
    name: "TERMINUS CORE",
    element: "QUANTUM",
    rarity: "gold",
    ratios: { hp: 113, mp: 114, str: 114, def: 107, ag: 116, mv: 14, xv: 15 },
    bio: "Veterano das arenas de QUANTUM. Assina cada vitória com REINICIAR REALIDADE.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["FEIXE DO NUCLEO", "GLITCH LETAL", "REINICIAR REALIDADE", "CUBO INVIOLAVEL"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "heliondriver",
    name: "HELION DRIVER",
    element: "SOL",
    rarity: "silver",
    ratios: { hp: 109, mp: 100, str: 105, def: 101, ag: 102, mv: 11, xv: 12 },
    bio: "Predador de SOL. Caça sistemas rivais e finaliza com EXPLOSAO DE CROMOSFERA.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.levelup,
    names: ["INVESTIDA SOLAR", "PROPULSAO MAXIMA", "EXPLOSAO DE CROMOSFERA", "AEROFOLIO BLINDADO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "noxfeather",
    name: "NOXFEATHER",
    element: "SOMBRA",
    rarity: "silver",
    ratios: { hp: 107, mp: 98, str: 120, def: 98, ag: 102, mv: 11, xv: 12 },
    bio: "Campeão de SOMBRA. Sua técnica GRASNADO MALDITO encerra duelos em um golpe.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["PENAS SOMBRIAS", "VOO NOTURNO", "GRASNADO MALDITO", "ASAS DE BREU"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "basaltguard",
    name: "BASALT GUARD",
    element: "OBSIDIANA",
    rarity: "bronze",
    ratios: { hp: 110, mp: 81, str: 96, def: 106, ag: 94, mv: 9, xv: 9 },
    bio: "Lenda do circuito de OBSIDIANA. Ninguém sobrevive a LASCAS VULCANICAS duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["COLUNA DE BASALTO", "IMPACTO ROCHOSO", "LASCAS VULCANICAS", "PILAR DEFENSIVO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "hexweaver",
    name: "HEXWEAVER",
    element: "GRAFENO",
    rarity: "silver",
    ratios: { hp: 111, mp: 106, str: 116, def: 101, ag: 109, mv: 11, xv: 12 },
    bio: "Piloto autônomo de GRAFENO. Guarda REDE PARALISANTE para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["TEIA HEXAGONAL", "PERNA CORTANTE", "REDE PARALISANTE", "CASULO DE GRAFENO"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "solstitia",
    name: "SOLSTITIA",
    element: "ECLIPSE",
    rarity: "silver",
    ratios: { hp: 101, mp: 108, str: 113, def: 109, ag: 103, mv: 11, xv: 12 },
    bio: "Piloto autônomo de ECLIPSE. Guarda EQUINOCIO para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["DISCO SOLSTICIO", "GIRO DUPLO", "EQUINOCIO", "CICLO PROTETOR"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "cometfang",
    name: "COMETFANG",
    element: "METEORO",
    rarity: "bronze",
    ratios: { hp: 115, mp: 96, str: 109, def: 109, ag: 94, mv: 9, xv: 9 },
    bio: "Piloto autônomo de METEORO. Guarda QUEDA DE COMETA para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CAUDA DE COMETA", "PRESA CONGELANTE", "QUEDA DE COMETA", "HALO GELADO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "orbitalmarshal",
    name: "ORBITAL MARSHAL",
    element: "ANEL",
    rarity: "gold",
    ratios: { hp: 109, mp: 117, str: 129, def: 99, ag: 116, mv: 14, xv: 15 },
    bio: "Chassi forjado para ANEL. Abre a guarda inimiga com BOMBARDEIO SATELITE.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ATAQUE ORBITAL", "ANEL DE COMANDO", "BOMBARDEIO SATELITE", "ESCUDO ESTACAO"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "neutronmaul",
    name: "NEUTRON MAUL",
    element: "PULSAR",
    rarity: "silver",
    ratios: { hp: 105, mp: 103, str: 111, def: 100, ag: 103, mv: 11, xv: 12 },
    bio: "Piloto autônomo de PULSAR. Guarda COMPRESSAO BRUTAL para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["MARRETA DE NEUTRONS", "PESO ESTELAR", "COMPRESSAO BRUTAL", "MATERIA DENSA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "eventhorizon",
    name: "EVENT HORIZON",
    element: "BURACO NEGRO",
    rarity: "gold",
    ratios: { hp: 103, mp: 110, str: 123, def: 101, ag: 111, mv: 14, xv: 15 },
    bio: "Chassi forjado para BURACO NEGRO. Abre a guarda inimiga com DILATACAO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CORTE SINGULAR", "ATRACAO INFINITA", "DILATACAO", "DISCO DE ACRECAO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "mossknight",
    name: "MOSS KNIGHT",
    element: "SELVA",
    rarity: "bronze",
    ratios: { hp: 113, mp: 80, str: 102, def: 111, ag: 97, mv: 9, xv: 9 },
    bio: "Piloto autônomo de SELVA. Guarda RAIZES PRENSANTES para o momento decisivo.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["ESPADA DE MADEIRA", "BROTO CORTANTE", "RAIZES PRENSANTES", "ESCUDO FLORIDO"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "quicksilverr",
    name: "QUICKSILVER",
    element: "ESPELHO",
    rarity: "gold",
    ratios: { hp: 112, mp: 119, str: 116, def: 111, ag: 101, mv: 14, xv: 15 },
    bio: "Lenda do circuito de ESPELHO. Ninguém sobrevive a GOTA LETAL duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["LAMINA LIQUIDA", "FORMA MUTAVEL", "GOTA LETAL", "SUPERFICIE ESPELHADA"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "boneorchestra",
    name: "BONE ORCHESTRA",
    element: "OSSO",
    rarity: "gold",
    ratios: { hp: 111, mp: 113, str: 120, def: 108, ag: 114, mv: 14, xv: 15 },
    bio: "Lenda do circuito de OSSO. Ninguém sobrevive a REQUIEM duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["BATUTA MORTAL", "SINFONIA DE OSSOS", "REQUIEM", "ORQUESTRA BLINDADA"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "stratoveil",
    name: "STRATOVEIL",
    element: "NUVEM",
    rarity: "silver",
    ratios: { hp: 104, mp: 107, str: 104, def: 96, ag: 111, mv: 11, xv: 12 },
    bio: "Chassi forjado para NUVEM. Abre a guarda inimiga com NEVOEIRO DENSO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["PALMA DE VAPOR", "CAMADA ESTRATO", "NEVOEIRO DENSO", "MANTO DE NUVENS"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "lavabastion",
    name: "LAVA BASTION",
    element: "VULCAO",
    rarity: "gold",
    ratios: { hp: 109, mp: 123, str: 128, def: 106, ag: 104, mv: 14, xv: 15 },
    bio: "Predador de VULCAO. Caça sistemas rivais e finaliza com CALDEIRA.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CANHAO DE CRATERA", "MURALHA DE LAVA", "CALDEIRA", "ESCUDO DE ROCHA IGNEA"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "bogtyrant",
    name: "BOG TYRANT",
    element: "PANTANO",
    rarity: "silver",
    ratios: { hp: 107, mp: 98, str: 104, def: 95, ag: 101, mv: 11, xv: 12 },
    bio: "Predador de PANTANO. Caça sistemas rivais e finaliza com LAMA FERVENTE.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["LINGUA CHICOTE", "ENGOLIR", "LAMA FERVENTE", "PELE VISCOSA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "mirageblade",
    name: "MIRAGE BLADE",
    element: "DESERTO",
    rarity: "gold",
    ratios: { hp: 101, mp: 118, str: 116, def: 113, ag: 102, mv: 14, xv: 15 },
    bio: "Lenda do circuito de DESERTO. Ninguém sobrevive a CALOR ILUSORIO duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.explosion,
    names: ["CIMITARRA MIRAGEM", "CORTE DE MIRAGEM", "CALOR ILUSORIO", "VEU DE MIRAGEM"],
    effect: { type: "blind", power: 25, turns: 3, chance: 0.75 },
  },
  {
    id: "permafrostmk",
    name: "PERMAFROST MK",
    element: "TUNDRA",
    rarity: "gold",
    ratios: { hp: 99, mp: 113, str: 119, def: 110, ag: 110, mv: 14, xv: 15 },
    bio: "Predador de TUNDRA. Caça sistemas rivais e finaliza com PERMAFROST.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["CANHAO DE GEADA", "BROCA POLAR", "PERMAFROST", "BLINDAGEM ARTICA"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "coralshiv",
    name: "CORAL SHIV",
    element: "RECIFE",
    rarity: "bronze",
    ratios: { hp: 110, mp: 85, str: 105, def: 102, ag: 91, mv: 9, xv: 9 },
    bio: "Lenda do circuito de RECIFE. Ninguém sobrevive a ESPINHO VENENOSO duas vezes.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ADAGA DE CORAL", "GOLPE RAPIDO", "ESPINHO VENENOSO", "ARMADURA DE CONCHA"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
  {
    id: "resinjudge",
    name: "RESIN JUDGE",
    element: "AMBAR",
    rarity: "silver",
    ratios: { hp: 106, mp: 100, str: 107, def: 109, ag: 111, mv: 11, xv: 12 },
    bio: "Campeão de AMBAR. Sua técnica PRISAO FOSSIL encerra duelos em um golpe.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["MARTELO DE AMBAR", "SENTENCA RESINOSA", "PRISAO FOSSIL", "TOGA ENDURECIDA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "gridrunner",
    name: "GRIDRUNNER",
    element: "NEON",
    rarity: "bronze",
    ratios: { hp: 114, mp: 95, str: 108, def: 112, ag: 88, mv: 9, xv: 9 },
    bio: "Piloto autônomo de NEON. Guarda SOBRECARGA para o momento decisivo.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["DISCO DE LUZ", "CORRIDA NA GRADE", "SOBRECARGA", "PAREDE DE DADOS"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "seraphimvoid",
    name: "SERAPHIM VOID",
    element: "VAZIO",
    rarity: "gold",
    ratios: { hp: 113, mp: 108, str: 119, def: 109, ag: 105, mv: 14, xv: 15 },
    bio: "Piloto autônomo de VAZIO. Guarda ABISMO SAGRADO para o momento decisivo.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.void,
    names: ["ASA CORROMPIDA", "QUEDA CELESTIAL", "ABISMO SAGRADO", "AUREOLA QUEBRADA"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "tempestcrown",
    name: "TEMPEST CROWN",
    element: "TEMPESTADE",
    rarity: "gold",
    ratios: { hp: 108, mp: 124, str: 126, def: 112, ag: 109, mv: 14, xv: 15 },
    bio: "Veterano das arenas de TEMPESTADE. Assina cada vitória com TEMPESTADE REAL.",
    vfxStrong: VFX.thunder,
    vfxSpecial: VFX.thunder,
    names: ["CETRO GEMEO", "COROA DE TROVAO", "TEMPESTADE REAL", "OLHO DO FURACAO"],
    effect: { type: "paralyze", power: 0, turns: 2, chance: 0.5 },
  },
  {
    id: "ironmonarch",
    name: "IRON MONARCH",
    element: "FERRO",
    rarity: "gold",
    ratios: { hp: 111, mp: 119, str: 118, def: 101, ag: 116, mv: 14, xv: 15 },
    bio: "Veterano das arenas de FERRO. Assina cada vitória com EXECUCAO REAL.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.shield,
    names: ["MONTANTE DE FERRO", "DECRETO DE ACO", "EXECUCAO REAL", "COURACA IMPERIAL"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "vireoblade",
    name: "VIREO BLADE",
    element: "JADE",
    rarity: "silver",
    ratios: { hp: 112, mp: 99, str: 117, def: 95, ag: 109, mv: 11, xv: 12 },
    bio: "Lenda do circuito de JADE. Ninguém sobrevive a VENTO VERDE duas vezes.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["CORTE DE BAMBU", "LAMINA DE JADE", "VENTO VERDE", "POSTURA SERENA"],
    effect: { type: "weakening", power: 28, turns: 3, chance: 0.75 },
  },
  {
    id: "aetherloom",
    name: "AETHER LOOM",
    element: "NEBULOSA",
    rarity: "gold",
    ratios: { hp: 107, mp: 121, str: 123, def: 104, ag: 111, mv: 14, xv: 15 },
    bio: "Chassi forjado para NEBULOSA. Abre a guarda inimiga com TECER DESTINO.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["FIO ESTELAR", "TEAR COSMICO", "TECER DESTINO", "TAPECARIA BLINDADA"],
    effect: { type: "trapped", power: 0, turns: 3, chance: 0.5 },
  },
  {
    id: "cindercrown",
    name: "CINDER CROWN",
    element: "CINZAS",
    rarity: "silver",
    ratios: { hp: 107, mp: 111, str: 115, def: 99, ag: 109, mv: 11, xv: 12 },
    bio: "Chassi forjado para CINZAS. Abre a guarda inimiga com TEMPESTADE DE CINZAS.",
    vfxStrong: VFX.impact,
    vfxSpecial: VFX.explosion,
    names: ["ESPADA DE CINZAS", "COROA RUIDA", "TEMPESTADE DE CINZAS", "MANTO CINZENTO"],
    effect: { type: "burn", power: 14, turns: 3, chance: 0.75 },
  },
  {
    id: "magnetarfist",
    name: "MAGNETAR FIST",
    element: "MAGNETISMO",
    rarity: "gold",
    ratios: { hp: 100, mp: 117, str: 116, def: 111, ag: 110, mv: 14, xv: 15 },
    bio: "Lenda do circuito de MAGNETISMO. Ninguém sobrevive a PULSO MAGNETICO duas vezes.",
    vfxStrong: VFX.void,
    vfxSpecial: VFX.thunder,
    names: ["PUNHO MAGNETAR", "ATRACAO DE SUCATA", "PULSO MAGNETICO", "CAMPO POLARIZADO"],
    effect: { type: "drain", power: 15, turns: 3, chance: 0.75 },
  },
  {
    id: "ravenousbloom",
    name: "RAVENOUS BLOOM",
    element: "BIO",
    rarity: "gold",
    ratios: { hp: 111, mp: 110, str: 119, def: 108, ag: 102, mv: 14, xv: 15 },
    bio: "Campeão de BIO. Sua técnica SEIVA CORROSIVA encerra duelos em um golpe.",
    vfxStrong: VFX.slash,
    vfxSpecial: VFX.heal,
    names: ["MORDIDA FLORAL", "ESPINHOS VORAZES", "SEIVA CORROSIVA", "BOTAO BLINDADO"],
    effect: { type: "poison", power: 16, turns: 3, chance: 0.75 },
  },
];

export const ROBOTS: RobotDef[] = BLUEPRINTS.map((b) => ({
  id: b.id,
  name: b.name,
  element: b.element,
  rarity: b.rarity,
  ratios: b.ratios,
  bio: b.bio,
  skills: buildSkills(b),
}));

export const ROBOT_MAP: Record<string, RobotDef> = Object.fromEntries(
  ROBOTS.map((r) => [r.id, r]),
);

export const STARTER_ROBOTS = ["aurorion", "ferrovax", "cryolance", "voltronin"];

// Sprite: strip horizontal de 16 frames de 128px.
export const FRAME = 128;
export const FRAMES = 16;
export const ANIM = {
  idle: [0, 1, 2, 3],
  attack: [4, 5, 6, 7],
  damage: [8, 9],
  guard: [10, 11],
  enter: [12, 13, 14, 15],
} as const;

export function spriteUrl(id: string): string {
  return `/robots/${id}.png`;
}

export function faceUrl(id: string): string {
  return `/robots/${id}_face.png`;
}
